### ISSUE TITLE
Rename example.xsd

### ISSUE THREAD

**Issue by skeys** [IAU-ADES/xsd#12]
How about "exchange.xsd" for our most general format?  Mike suggested this and I liked it.

**Comment by schastel** [comment]
+1 for "exchange.xsd" defining the high-level
What about the include(s):
- ades.xsd for base data types sounds good to me;
- I suggest mpc.xsd for the enum values supported by the MPC (obs codes,
  etc.)

**Comment by skeys** [comment]
example renamed to exchange.
