### ISSUE TITLE
Consecutive observationContext or observations in observationBatch

### ISSUE THREAD

**Issue by skeys** [IAU-ADES/xsd#2]
observationBatch (in example.xsd) probably isn't quite right.  It currently allows consecutive observationContext or observations.  Should probably be redefined to disallow this.

**Comment by schastel** [comment]
I'm not sure of what is wanted here. 

Is it an alternation of  observationContext and observations? like:

```
<observationContext>[...]</observationContext>
<observations>[...]</observations>
<observationContext>[...]</observationContext>
<observations>[...]</observations>
```

(Trick = 3 backticks to display code)

**Comment by schastel** [comment]
Sorry. (Trick = 3 backticks to display code) 
```
<observationContext>[...]</observationContext>
<observations>[...]</observations>
<observationContext>[...]</observationContext>
<observations>[...]</observations>
```

**Comment by skeys** [comment]
For MPC submissions, I think so.  Otherwise, it's not clear if there will be other uses for the observatonBatch element.  observationBatch and observationContext are currently in both example.xsd and submit.xsd.  They wouldn't have to stay the same.  MPCs submissions might require alternation, but the schema for more general purposes might allow more flexibility.  Considering just the definition in example.xsd for now, some possible options are
- Leave it with its current generality.
- Make it a little more restrictive, disallowing things that might seem odd, like `<context><context><obs><obs>`.
- Make it match whatever is in submit.xsd.
- Remove it from example.xsd, leaving observationBatch and observationContext defined only in submit.xsd.

**Comment by schastel** [comment]
Just tested it (see submit_ko_01.xml), the definition of observationBatch (as an unbounded sequence on context and then observations) prevents having two contexts or two observations elements in a row (e.g. context, context, observations...)
