### ISSUE TITLE
Field/element ordering

### ISSUE THREAD

**Issue by skeys** [IAU-ADES/xsd#5]
Should we put it into the ADES as a rule that fields must be in the specified order? It currently says "The number of fields present in a file and their order, should be flexible so that unused fields can be neglected." The justification there doesn't seem to apply to order. Unused fields could be neglected while still requiring that used fields are ordered. I used all to follow the ADES but requiring order sounds good to me.  The rule could cover other elements as well, for example to specify order for the observation header/observationContext element.

I think the rule would mostly help human readability by presenting fields in a familiar order.

**Comment by schastel** [comment]
Yes (my opinion and my opinion only)

**Comment by stevechesley** [comment]
Just wondering if there needs to be an ordering requirement on input. If a standard order is used on output then it seems to serve the purpose without breaking things if somebody happens to transpose some elements.

**Comment by skeys** [comment]
That sounds good to me, Steve.

So to define the order, I think it would be nice if the stn field were first within observations.  Since it is mandatory for all observation records, it would be convenient for detecting the start of a data block within a PSV file.

**Comment by stevechesley** [comment]
Please take a look at the table on page 23. http://minorplanetcenter.net/iau/info/IAU2015_ADES.pdf This prescribes the default format for PSV and was negotiated with Micheli, representing the small scale observing community. If we wish to change this then we need to go back to him, but I don't see a good reason to change the PSV. 

I doubt anybody cares much about the XML output order, but it could make some sense to follow more or less the same order, except that null fields would not appear in the XML while they would for the default PSV. PSV output should include the option for compact PSV (dropping null fields and field widths given by the maximum in the file) and default PSV (all fields at the width specified in the table).

On a (potentially) separate issue, I have the idea that PSV will be immediately converted (internally) to XML strings and then passed to XML validation and processing routines. No explicit validation of PSV. Similarly, on output, XML strings would be passed to a PSV conversion routine before writing to file. When Larry was here we more or less agreed on this scheme to avoid too much hassle with PSV. If this is not what you have in mind then you might open a new Issue on the topic for discussion.

**Comment by skeys** [comment]
My main issue is that the current rule for recognizing column headers requires the permID field to be present even though it will be blank for all new object submissions.  We could shrug our shoulders at the wasted storage but this also means that this initial blank column will take up space on the screen for anyone viewing the file.  Also permID is not a required field otherwise.  I would rather minimize the number of quirks where PSV rules are different than XML rules.  I thought we could do better by making stn first.  It is already required to be present in all cases and represents information of greater interest when presented on the screen.

On the separate issue, that all sounds good and I don't think we have any differences.  My PSV converter does just what you described, convert to XML then validate.

**Comment by skeys** [comment]
abandoned
